### PR TITLE
Upgrade to sentry/sdk 2.0.3

### PR DESCRIPTION
**Pull request by roelvanhintum**

### CODE REVIEW

**Comment by karensg** [comment]
@lukeyouell, please merge :)

**Comment by boboldehampsink** [comment]
@roelvanhintum can you create a new plugin for this? would love to use that.

**Comment by roelvanhintum** [comment]
@boboldehampsink you are welcome. ;) It is rewritten almost entirely.
https://github.com/born05/craft-sentry

The config is only a php file, which uses craft's environment and doesn't log in devmode. Also has the option to anonymize by not sending user info.

**Comment by karensg** [comment]
Awesome, going to try out this week

**Pull request closed without merging**
